baseURL: https://bibledelight.com/
languageCode: en-us
title: Bible Delight
theme: papermod
paginate: 10
params:
  description: Lists and evaluates Bible reading plans and related tools and thoughts in Scripture intake.
  datesinlist: 1
  disableThemeToggle: false
  ShowReadingTime: false
  mainSections:
    - plans
    - bibles
    - tools
    - thoughts

related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 50
  - name: date
    weight: 10
  threshold: 80
  toLower: false
      
      
menu:
  main:
    - identifier: plans
      name: Plans
      url: /plans/
      weight: 20
    - identifier: bibles
      name: Bibles
      url: /bibles/
      weight: 30
    - identifier: tools
      name: Tools
      url: /tools/
      weight: 40
    - identifier: thoughts
      name: Thoughts
      url: /thoughts/
      weight: 50

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 75
  resampleFilter: Box
  
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
