baseURL = 'http://bibledelight.netlify.app/'
languageCode = 'en-us'
title = 'Bible Delight'
theme = 'papermod'
enableGitInfo = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[params]
	datesinlist=1
	disableThemeToggle = false
	ShowReadingTime = true
		
[related]
  includeNewer = true
  threshold = 75
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10


